//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CuentasFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CREDITO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CREDITO()
        {
            this.ABONOes = new HashSet<ABONO>();
            this.MONTOCREDITOes = new HashSet<MONTOCREDITO>();
        }
    
        public int IdCredito { get; set; }
        public Nullable<int> IdEstado { get; set; }
        public string Detalle { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<int> IdCliente { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ABONO> ABONOes { get; set; }
        public virtual CLIENTE CLIENTE { get; set; }
        public virtual ESTADOCREDITO ESTADOCREDITO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MONTOCREDITO> MONTOCREDITOes { get; set; }
    }
}
