//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CuentasFinal.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class pruebaEntities : DbContext
    {
        public pruebaEntities()
            : base("name=pruebaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ABONO> ABONOes { get; set; }
        public virtual DbSet<CLIENTE> CLIENTEs { get; set; }
        public virtual DbSet<CREDITO> CREDITOes { get; set; }
        public virtual DbSet<DETALLEFACTURA> DETALLEFACTURAs { get; set; }
        public virtual DbSet<ESTADOCREDITO> ESTADOCREDITOes { get; set; }
        public virtual DbSet<FACTURA> FACTURAs { get; set; }
        public virtual DbSet<MONTOCREDITO> MONTOCREDITOes { get; set; }
        public virtual DbSet<PRODUCTO> PRODUCTOes { get; set; }
        public virtual DbSet<RECIBOCAJA> RECIBOCAJAs { get; set; }
        public virtual DbSet<SALDO> SALDOes { get; set; }
        public virtual DbSet<TIPOCLIENTE> TIPOCLIENTEs { get; set; }
        public virtual DbSet<TIPOPAGO> TIPOPAGOes { get; set; }
        public virtual DbSet<USUARIO> USUARIOs { get; set; }
    }
}
