//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CuentasFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MONTOCREDITO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MONTOCREDITO()
        {
            this.SALDOes = new HashSet<SALDO>();
        }
    
        public int IdMonto { get; set; }
        public Nullable<decimal> Monto { get; set; }
        public Nullable<int> IdCredito { get; set; }
    
        public virtual CREDITO CREDITO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SALDO> SALDOes { get; set; }
    }
}
