//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CuentasFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SALDO
    {
        public int IdSaldo { get; set; }
        public Nullable<decimal> Monto { get; set; }
        public Nullable<int> IdMonto { get; set; }
        public Nullable<int> IdFactura { get; set; }
        public Nullable<int> IdAbono { get; set; }
    
        public virtual ABONO ABONO { get; set; }
        public virtual FACTURA FACTURA { get; set; }
        public virtual MONTOCREDITO MONTOCREDITO { get; set; }
    }
}
