//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CuentasFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIO
    {
        public int IdUser { get; set; }
        public string Nombre { get; set; }
        public Nullable<int> Telefono { get; set; }
        public string Puesto { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
    }
}
